# Generated by Django 6.0.3 on 2026-04-01 08:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='الاسم (اختياري)')),
                ('gender', models.CharField(choices=[('male', 'ذكر'), ('female', 'أنثى')], max_length=10, verbose_name='النوع')),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(17), django.core.validators.MaxValueValidator(35)], verbose_name='السن')),
                ('college', models.CharField(max_length=100, verbose_name='الكلية')),
                ('year', models.CharField(choices=[('1', 'الفرقة الأولى'), ('2', 'الفرقة الثانية'), ('3', 'الفرقة الثالثة'), ('4', 'الفرقة الرابعة')], max_length=1, verbose_name='الفرقة الدراسية')),
                ('primary_website', models.CharField(choices=[('sports', 'الرياضية'), ('entertainment', 'الفنية'), ('educational', 'التعليمية'), ('political', 'السياسية'), ('other', 'أخرى')], max_length=20, verbose_name='أهم المواقع المستخدمة')),
                ('other_website', models.CharField(blank=True, max_length=100, null=True, verbose_name='مواقع أخرى')),
                ('computer_skill', models.CharField(choices=[('beginner', 'مبتدئ'), ('intermediate', 'متوسط'), ('advanced', 'متقدم')], max_length=15, verbose_name='مهارة استخدام الحاسوب')),
                ('daily_hours', models.CharField(choices=[('less_than_1', 'أقل من ساعة'), ('1_to_2', 'من ساعة إلى ساعتين'), ('3_to_4', 'من ثلاثة ساعات إلى أربعة ساعات'), ('5_to_6', 'من خمس ساعات إلى ستة ساعات'), ('more', 'أكثر من ذلك')], max_length=15, verbose_name='عدد الساعات اليومية')),
                ('other_hours', models.CharField(blank=True, max_length=100, null=True, verbose_name='ساعات أخرى')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ المشاركة')),
            ],
            options={
                'verbose_name': 'مشارك',
                'verbose_name_plural': 'المشاركون',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='نص السؤال')),
                ('category', models.CharField(choices=[('internet_usage_goal', 'الهدف من استخدام الإنترنت'), ('isolation_reality', 'واقع تفشي ظاهرة العزلة الإلكترونية'), ('academic_impact', 'تأثير العزلة الإلكترونية على التحصيل الدراسي'), ('social_impact', 'تأثير العزلة الإلكترونية على العلاقات الاجتماعية'), ('psychological_impact', 'تأثير العزلة الإلكترونية على الحالة النفسية'), ('suggestions', 'المقترحات للتخفيف من الآثار السلبية')], max_length=25, verbose_name='التصنيف')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'سؤال',
                'verbose_name_plural': 'الأسئلة',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='SurveyResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('internet_usage_goal', 'الهدف من استخدام الإنترنت'), ('isolation_reality', 'واقع تفشي ظاهرة العزلة الإلكترونية'), ('academic_impact', 'تأثير العزلة الإلكترونية على التحصيل الدراسي'), ('social_impact', 'تأثير العزلة الإلكترونية على العلاقات الاجتماعية'), ('psychological_impact', 'تأثير العزلة الإلكترونية على الحالة النفسية'), ('suggestions', 'المقترحات للتخفيف من الآثار السلبية')], max_length=25, verbose_name='التصنيف')),
                ('total_answers', models.PositiveIntegerField(default=0, verbose_name='إجمالي الإجابات')),
                ('yes_count', models.PositiveIntegerField(default=0, verbose_name='عدد نعم')),
                ('somewhat_count', models.PositiveIntegerField(default=0, verbose_name='عدد إلى حد ما')),
                ('no_count', models.PositiveIntegerField(default=0, verbose_name='عدد لا')),
                ('yes_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة نعم')),
                ('somewhat_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة إلى حد ما')),
                ('no_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة لا')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'نتيجة الاستبيان',
                'verbose_name_plural': 'نتائج الاستبيان',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(choices=[('yes', 'نعم'), ('somewhat', 'إلى حد ما'), ('no', 'لا')], max_length=10, verbose_name='الإجابة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='survey.participant', verbose_name='المشارك')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='survey.question', verbose_name='السؤال')),
            ],
            options={
                'verbose_name': 'إجابة',
                'verbose_name_plural': 'الإجابات',
                'ordering': ['-created_at'],
                'unique_together': {('participant', 'question')},
            },
        ),
    ]
