# Generated by Django 5.2.12 on 2026-04-07 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='email',
            field=models.EmailField(blank=True, max_length=150, null=True, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AddField(
            model_name='participant',
            name='university',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='الجامعة'),
        ),
    ]
